services:
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=cardgame
      - DB_PASSWORD=cardgamepass
      - DB_NAME=cardgamedb
      - DATABASE_URL=postgres://cardgame:cardgamepass@db:5432/cardgamedb
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: cardgame
      POSTGRES_PASSWORD: cardgamepass
      POSTGRES_DB: cardgamedb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
