services:
  frontend:
    build:
      context: ./frontend
      target: prod
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-card-game}
      DB_PASSWORD: ${DB_PASSWORD:-changeme}
      DB_NAME: ${DB_NAME:-card-game-db}
      DATABASE_URL: postgres://${DB_USER:-card-game}:${DB_PASSWORD:-changeme}@db:5432/${DB_NAME:-card-game-db}
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-card-game}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
      POSTGRES_DB: ${DB_NAME:-card-game-db}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  # Selenium Grid Hub
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  # Chrome Node
  selenium-chrome:
    image: selenium/node-chrome:4.15.0
    container_name: selenium-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

  # Firefox Node
  selenium-firefox:
    image: selenium/node-firefox:4.15.0
    container_name: selenium-firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

  # Selenium Tests
  selenium-tests:
    build: ./selenium
    container_name: selenium-tests
    depends_on:
      - selenium-hub
      - selenium-chrome
      - selenium-firefox
    environment:
      SELENIUM_REMOTE_URL: http://selenium-hub:4444/wd/hub
    ports:
      - "8080:8080"
    command: ["sh", "-c", "sleep 10 && npm run test:grid"]

volumes:
  db-data:
