name: CI
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "LICENSE"
      - "CHANGELOG.md"
      - "CONTRIBUTING.md"
      - "CODE_OF_CONDUCT.md"
      - "PULL_REQUEST_TEMPLATE.md"
      - "ISSUE_TEMPLATE.md"
  pull_request:
    branches:
      - main

jobs:
  frontend-ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Chrome dependencies (before firewall)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libnss3 libgdk-pixbuf-2.0-0 libgtk-3-0 libx11-xcb1 libxcomposite1 libxrandr2 libxi6 \
            libasound2 libpangocairo-1.0-0 libxdamage1 libpango-1.0-0 libatk1.0-0 libatk-bridge2.0-0 \
            libcups2 libdrm2 libgbm1 libxcb1 libxshmfence1

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build (production)
        run: npm run build -- --configuration production
        working-directory: ./frontend

      - name: Run unit tests (headless Chrome with coverage)
        run: npm run test:ci
        working-directory: ./frontend
        env:
          # Configure Chrome for CI environment
          CHROME_BIN: /usr/bin/google-chrome
          CHROME_FLAGS: >-
            --no-sandbox
            --disable-dev-shm-usage
            --disable-background-networking
            --disable-default-apps
            --disable-extensions
            --disable-sync
            --disable-translate
            --hide-scrollbars
            --metrics-recording-only
            --mute-audio
            --no-first-run
            --safebrowsing-disable-auto-update
            --disable-background-timer-throttling
            --disable-renderer-backgrounding
            --disable-backgrounding-occluded-windows
            --disable-features=TranslateUI,BlinkGenPropertyTrees

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage
          if-no-files-found: warn